package com.huddle01.kotlin_client.types

enum class HandlerEvents {
    HELLO,
    WAITINGROOM,
    CONNECTROOMRESPONSE,
    CREATETRANSPORTONCLIENT,
    SYNCMEETINGSTATERESPONSE,
    CONNECTTRANSPORTRESPONSE,
    PRODUCERESPONSE,
    CONSUMERESPONSE,
    CLOSEPRODUCERSUCCESS,
    CLOSECONSUMERSUCCESS,
    RESTARTTRANSPORTICERESPONSE,
    NEWPEERJOINED,
    NEWLOBBYPEER,
    NEWPERMISSIONS,
    NEWROOMCONTROLS,
    NEWPEERROLE,
    ROOMCLOSEDPRODUCERS,
    RECEIVEDATA,
    PEERMETADATAUPDATED,
    ROOMMETADATAUPDATED,
    PEERLEFT,
    LOBBYPEERLEFT,
    ERROR;
}